project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls')),
]

project_tracker/tasks/urls.py
from django.urls import path

from tasks import views

app_name = 'tasks'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('projects/', views.project_list, name='project_list'),
    # path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),

    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('project/new/', views.create_project, name='create_project'),
    path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
]

project_tracker/tasks/models.py
from django.contrib.auth.models import User
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    STATUS_CHOICES = (
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена')
    )
    project = models.ForeignKey(
        Project,
        related_name='tasks',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    assignee = models.ForeignKey(
        User,
        related_name='tasks',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New'
    )

    def __str__(self):
        return self.name

project_tracker/tasks/forms.py
from django import forms


class FeedbackForm(forms.Form):
    name = forms.CharField(label='Ваше имя', max_length=100)
    email = forms.EmailField(label='Электронная почта')
    message = forms.CharField(widget=forms.Textarea, label='Сообщение')


from django.forms import ModelForm

from .models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'description')


from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description', 'status', 'assignee')

project_tracker/tasks/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy

from .models import Project, Task


def index(request):
    return render(request, 'tasks/index.html')


def project_list(request):
    projects = Project.objects.all()
    return render(request, 'tasks/project_list.html', {'project_list': projects})


def project_detail(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    return render(request, 'tasks/project_detail.html', {'project': project})


def task_detail(request, project_id, task_id):
    task = get_object_or_404(Task, id=task_id, project_id=project_id)
    return render(request, 'tasks/task_detail.html', {'task': task})


from django.core.mail import send_mail

from .forms import ProjectForm, TaskForm


def create_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:project_list')
    else:
        form = ProjectForm()
    return render(request, 'tasks/project_create.html', {'form': form})


def add_task_to_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.project = project
            task.save()
            return redirect('tasks:project_detail', project_id=project.id)
    else:
        form = TaskForm()
    return render(request, 'tasks/add_task.html', {'form': form, 'project': project})


def update_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('tasks:project_detail', project_id=project.id)
    else:
        form = ProjectForm(instance=project)
    return render(request, 'tasks/project_update.html', {'form': form, 'project': project})


def update_task(request, project_id, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('tasks:task_detail', project_id=project_id, task_id=task.id)
    else:
        form = TaskForm(instance=task)
    return render(request, 'tasks/task_update.html', {'form': form, 'task': task})


def delete_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    project.delete()
    return redirect('tasks:project_list')


def delete_task(request, project_id, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return redirect('tasks:project_detail', project_id=project_id)


from django.views import View


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'tasks/index.html')


from django.views.generic import ListView, CreateView, UpdateView


class ProjectListView(ListView):
    model = Project
    template_name = 'tasks/project_list.html'


from django.views.generic import DetailView


class ProjectDetailView(DetailView):
    model = Project
    pk_url_kwarg = 'project_id'
    template_name = 'tasks/project_detail.html'


class TaskDetailView(DetailView):
    model = Task
    pk_url_kwarg = 'task_id'
    template_name = 'tasks/task_detail.html'


class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'tasks/project_create.html'
    success_url = reverse_lazy('tasks:project_list')


class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/add_task.html'

    def form_valid(self, form):
        form.instance.project = get_object_or_404(Project, id=self.kwargs['project_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('tasks:project_detail', kwargs={'project_id': self.kwargs['project_id']})


class ProjectUpdateView(UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'tasks/project_update.html'
    pk_url_kwarg = 'project_id'
    success_url = reverse_lazy('tasks:project_list')


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/task_update.html'
    pk_url_kwarg = 'task_id'

    def get_success_url(self):
        return reverse_lazy('tasks:task_detail',
                            kwargs={'project_id': self.object.project.id, 'task_id': self.object.id})


from django.views.generic.edit import DeleteView


class ProjectDeleteView(DeleteView):
    model = Project
    pk_url_kwarg = 'project_id'
    success_url = reverse_lazy('tasks:project_list')
    template_name = 'tasks/project_confirm_delete.html'


class TaskDeleteView(DeleteView):
    model = Task
    pk_url_kwarg = 'task_id'

    def get_success_url(self):
        return reverse_lazy('tasks:project_detail', kwargs={'project_id': self.object.project.id})

project_tracker/tasks/templates/tasks/add_task.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Добавить задачу в проект {{ project.name }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать задачу</button>
  </form>
{% endblock %}

project_tracker/tasks/templates/tasks/feedback.html
{% extends 'base/base.html' %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
  </form>
{% endblock %}

project_tracker/tasks/templates/tasks/index.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Страница приложения tasks</h1>
  <a href="{% url 'tasks:project_list' %}">Список проектов</a>
{% endblock %}

project_tracker/tasks/templates/tasks/project_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Удаление проекта</h1>
  <p>Вы уверены, что хотите удалить проект "{{ project.name }}"?</p>
  <form action="{% url 'tasks:delete_project' project.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
    <a href="{% url 'tasks:project_detail' project.id %}">Отмена</a>
  </form>
{% endblock %}

project_tracker/tasks/templates/tasks/project_create.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Создать новый проект</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
  </form>
{% endblock %}

project_tracker/tasks/templates/tasks/project_detail.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>{{ project.name }}</h1>
  <p>{{ project.description }}</p>
  
  <p><a href="{% url 'tasks:update_project' project.id %}">Изменить проект</a></p>
  
  <p><a href="{% url 'tasks:add_task_to_project' project.id %}">Добавить новую задачу</a></p>
  
  <p><a href="{% url 'tasks:delete_project' project.id %}"
        onclick="return confirm('Вы уверены, что хотите удалить этот проект?');">Удалить проект</a></p>
  
  <h2>Задачи в проекте</h2>
  <ul>
    {% for task in project.tasks.all %}
      <li><a href="{% url 'tasks:task_detail' project.id task.id %}">{{ task.name }} - {{ task.status }}</a></li>
    {% empty %}
      <li>В этом проекте пока нет задач.</li>
    {% endfor %}
  </ul>

{% endblock %}

project_tracker/tasks/templates/tasks/project_list.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Список проектов</h1>
  
  <p><a href="{% url 'tasks:create_project' %}">Создать новый проект</a></p>
  
  <ul>
    {% for project in project_list %}
      <li><a href="{% url 'tasks:project_detail' project.id %}">{{ project.name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

project_tracker/tasks/templates/tasks/project_update.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Изменение проекта: {{ project.name }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

project_tracker/tasks/templates/tasks/task_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Удаление задачи</h1>
  <p>Вы уверены, что хотите удалить задачу "{{ task.name }}"?</p>
  <form action="{% url 'tasks:delete_task' task.project.id task.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
    <a href="{% url 'tasks:task_detail' task.project.id task.id %}">Отмена</a>
  </form>
{% endblock %}

project_tracker/tasks/templates/tasks/task_detail.html
{% extends 'base/base.html' %}

{% block content %}
  <p><a href="{% url 'tasks:update_task' project_id=task.project.id task_id=task.id %}">Изменить задачу</a></p>
  
  <p><a href="{% url 'tasks:delete_task' project_id=task.project.id task_id=task.id %}"
        onclick="return confirm('Вы уверены, что хотите удалить эту задачу?');">Удалить задачу</a></p>
  
  <h1>{{ task.name }}</h1>
  <p>Статус: {{ task.status }}</p>
  <p>Описание: {{ task.description }}</p>
{% endblock %}

project_tracker/tasks/templates/tasks/task_update.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Изменение задачи: {{ task.name }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}