project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls')),
]

project_tracker/quality_control/urls.py
from django.urls import path

from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('bugs/', views.bug_list, name='bug_list'),
    # path('features/', views.feature_list, name='feature_list'),
    # path('bugs/<int:bug_id>/', views.bug_detail, name='bug_detail'),
    # path('features/<int:feature_id>/', views.feature_detail, name='feature_id_detail'),
    # path('bugs/bug_report_form/', views.create_bug_report, name='bug_report_form'),
    # path('features/feature_request_form/', views.create_feature_request, name='feature_request_form'),
    # path('bugs/<int:bug_id>/update/', views.update_bug_report, name='update_bug_report'),
    # path('features/<int:feature_id>/update/', views.update_feature_request, name='update_feature_request'),
    # path('bugs/<int:bug_id>/delete/', views.delete_bug_report, name='delete_bug_report'),
    # path('features/<int:feature_id>/delete/', views.delete_feature_request, name='delete_feature_request'),

    path('', views.IndexView.as_view(), name='index'),
    path('bugs/', views.BugListView.as_view(), name='bug_list'),
    path('features/', views.FeatureListView.as_view(), name='feature_list'),
    path('bugs/<int:bug_id>/', views.BugDetailView.as_view(), name='bug_detail'),
    path('features/<int:feature_id>/', views.FeatureDetailView.as_view(), name='feature_id_detail'),
    path('bugs/bug_report_form/', views.CreateBugReport.as_view(), name='bug_report_form'),
    path('features/feature_request_form/', views.CreateFeatureRequest.as_view(), name='feature_request_form'),
    path('bugs/<int:bug_id>/update/', views.UpdateBugReport.as_view(), name='update_bug_report'),
    path('features/<int:feature_id>/update/', views.UpdateFeatureRequest.as_view(), name='update_feature_request'),
    path('bugs/<int:bug_id>/delete/', views.DeleteBugReport.as_view(), name='delete_bug_report'),
    path('features/<int:feature_id>/delete/', views.DeleteFeatureRequest.as_view(), name='delete_feature_request'),

]

project_tracker/tasks/urls.py
from django.urls import path

from tasks import views

app_name = 'tasks'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('projects/', views.project_list, name='project_list'),
    # path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),

    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('project/new/', views.create_project, name='create_project'),
    path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
]

project_tracker/quality_control/models.py
from django.db import models

from tasks.models import Project, Task


class BugReport(models.Model):
    STATUS_CHOICES = (
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена')
    )
    PRIORITY_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name='bug_reports',
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        related_name='bug_reports',
        null=True,
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New'
    )
    priority = models.PositiveSmallIntegerField(
        choices=PRIORITY_CHOICES,
        default=1,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class FeatureRequest(models.Model):
    STATUS_CHOICES = (
        ('Review', 'Рассмотрение'),
        ('Accepted', 'Принято'),
        ('Declined', 'Отклонено')
    )
    PRIORITY_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name='feature_requests',
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        related_name='feature_requests',
        null=True,
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='Review'
    )
    priority = models.PositiveSmallIntegerField(
        choices=PRIORITY_CHOICES,
        default=1,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

project_tracker/quality_control/forms.py
from django.forms import ModelForm, ChoiceField
from .models import BugReport, FeatureRequest
from tasks.models import Task, Project


class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'project', 'task', 'status', 'priority']


class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'project', 'task', 'status', 'priority']

project_tracker/quality_control/views.py
from django.forms import ModelChoiceField
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from tasks.models import Project, Task
from .models import BugReport, FeatureRequest
from .forms import BugReportForm, FeatureRequestForm


def index(request):
    return render(request, 'quality_control/index.html')


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')


def bug_list(request):
    bugreport_list = BugReport.objects.all()
    return render(request, 'quality_control/bug_list.html', {'bugreport_list': bugreport_list})


class BugListView(ListView):
    model = BugReport
    template_name = 'quality_control/bug_list.html'


def feature_list(request):
    featurerequest_list = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'featurerequest_list': featurerequest_list})


class FeatureListView(ListView):
    model = FeatureRequest
    template_name = 'quality_control/feature_list.html'


def bug_detail(request, bug_id):
    bugreport = get_object_or_404(BugReport, pk=bug_id)
    return render(request, 'quality_control/bug_detail.html', {'bugreport': bugreport})


class BugDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_detail.html'


def feature_detail(request, feature_id):
    featurerequest = get_object_or_404(FeatureRequest, pk=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'featurerequest': featurerequest})


class FeatureDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    template_name = 'quality_control/feature_detail.html'


def create_bug_report(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_list')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html', {'form': form})


class CreateBugReport(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_form.html'

    def get_success_url(self):
        return reverse('quality_control:bug_list')


def create_feature_request(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_list')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_request_form.html', {'form': form})


class CreateFeatureRequest(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_form.html'

    def get_success_url(self):
        return reverse('quality_control:feature_list')


def update_bug_report(request, bug_id):
    bug_report = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug_report)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_detail', bug_id=bug_report.id)
    else:
        form = BugReportForm(instance=bug_report)
    return render(request, 'quality_control/bug_report_update.html', {'form': form, 'bug_report': bug_report})


class UpdateBugReport(UpdateView):
    model = BugReport
    form_class = BugReportForm
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_report_update.html'

    def get_success_url(self):
        return reverse('quality_control:bug_detail', kwargs={'bug_id': self.object.id})


def update_feature_request(request, feature_id):
    feature_request = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature_request)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_id_detail', feature_id=feature_request.id)
    else:
        form = FeatureRequestForm(instance=feature_request)
    return render(request, 'quality_control/feature_request_update.html',
                  {'form': form, 'feature_request': feature_request})


class UpdateFeatureRequest(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    pk_url_kwarg = 'feature_id'
    template_name = 'quality_control/feature_request_update.html'

    def get_success_url(self):
        return reverse('quality_control:feature_id_detail', kwargs={'feature_id': self.object.id})


def delete_bug_report(request, bug_id):
    bug_report = get_object_or_404(BugReport, pk=bug_id)
    bug_report.delete()
    return redirect('quality_control:bug_list')


class DeleteBugReport(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bug_list')
    template_name = 'quality_control/bug_confirm_delete.html'


def delete_feature_request(request, feature_id):
    feature_request = get_object_or_404(FeatureRequest, pk=feature_id)
    feature_request.delete()
    return redirect('quality_control:feature_list')


class DeleteFeatureRequest(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feature_list')
    template_name = 'quality_control/feature_confirm_delete.html'

project_tracker/quality_control/templates/quality_control/bug_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Удаление отчета об ошибке</h1>
  <p>Вы уверены, что хотите удалить отчет "{{ bugreport.title }}"?</p>
  <form action="{% url 'quality_control:delete_bug_report' bugreport.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
    <a href="{% url 'quality_control:bug_list' %}">Отмена</a>
  </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>{{ bugreport.title }}</h1>
  
  <p><a href="{% url 'quality_control:update_bug_report' bugreport.id %}">Изменить отчет об ошибке</a></p>
  
  <p><a href="{% url 'quality_control:delete_bug_report' bugreport.id %}"
        onclick="return confirm('Вы уверены, что хотите удалить этот отчет?');">Удалить отчет об ошибке</a></p>
  
  <p>Связанный проект: <b>{{ bugreport.project }}</b></p>
  <p>Связанная задача: <b>{{ bugreport.task }}</b></p>
  <p>Статус: <b>{{ bugreport.status }}</b></p>
  <p>Приоритет: <b>{{ bugreport.priority }}</b></p>
  <p>Описание: {{ bugreport.description }}</p>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Cписок отчетов об ошибках</h1>
  
  <p><a href="{% url 'quality_control:bug_report_form' %}">Сообщить об ошибке</a></p>
  
  <ul>
    {% for bug_report in bugreport_list %}
      <li>
        <h2>{{ bug_report.title }}</h2>
        Статус: {{ bug_report.status }}
        <br>
        <a href="{% url 'quality_control:bug_detail' bug_report.id %}">Детальное представление</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Добавить отчет об ошибке</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать отчет</button>
  </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_report_update.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Изменение отчета об ошибке: {{ bug_report.name }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Удаление запроса на улучшение</h1>
  <p>Вы уверены, что хотите удалить улучшение "{{ featurerequest.title }}"?</p>
  <form action="{% url 'quality_control:delete_feature_request' featurerequest.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
    <a href="{% url 'quality_control:feature_list' %}">Отмена</a>
  </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Информация по улучшению: {{ featurerequest.title }}</h1>
  
  <p><a href="{% url 'quality_control:update_feature_request' featurerequest.id %}">Изменить запрос на улучшение</a></p>
  
  <p><a href="{% url 'quality_control:delete_feature_request' featurerequest.id %}"
        onclick="return confirm('Вы уверены, что хотите удалить этот запрос?');">Удалить запрос на улучшение</a></p>
  
  <p>Связанный проект: <b>{{ featurerequest.project }}</b></p>
  <p>Связанная задача: <b>{{ featurerequest.task }}</b></p>
  <p>Статус: <b>{{ featurerequest.status }}</b></p>
  <p>Приоритет: <b>{{ featurerequest.priority }}</b></p>
  <p>Описание: {{ featurerequest.description }}</p>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Cписок улучшений</h1>
  
  <p><a href="{% url 'quality_control:feature_request_form' %}">Предложить улучшение</a></p>
  
  <ul>
    {% for feature in featurerequest_list %}
      <li>
        <h2>{{ feature.title }}</h2>
        Статус: {{ feature.status }}
        <br>
        <a href="{% url 'quality_control:feature_id_detail' feature.id %}">Детальное представление</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Создать запрос на улучшение</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить улучшение</button>
  </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_request_update.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Изменение запроса на улучшение: {{ feature_request.name }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
  <h1>Система контроля качества</h1>
  <a href="{% url 'quality_control:bug_list' %}">Список всех багов</a>
  <br>
  <a href="{% url 'quality_control:feature_list' %}">Запросы на улучшение</a>
{% endblock %}